@startuml

class Sender {
  + send(msg: Command, rec: Receiver)
}

class Receiver

interface Command<E> {
  + execute(): E
}

class KillConnection implements Command
class NotifyUser     implements Command
class PrintLogs      implements Command
class DisplayWebPage implements Command

Sender ..> Receiver
Sender ..> Command

@enduml
