@startuml

interface Element<E> {
  + getVal(): E
}

class Primitive<E> {
  + getVal(): E
}

class Group  {
  - elems: Element<E> [*]
  + getVal(): E
}

Group     o-- Element
Group     ..> Element
Primitive ..up.|> Element

@enduml
