@startuml

interface CreatesProduct {
  + Product makeProduct()
}

abstract class Product {
  ...
}

class OldProduct extends Product {
  ...
}

class FancyProduct extends Product {
  ...
}

class NewFactory implements CreatesProduct {
  + makeProduct(): Product
}

class OldFactory implements CreatesProduct {
  + makeProduct(): Product
}

@enduml
